[package]
name = "datadog"
version = "0.1.0"
edition = "2024"


[dependencies]
notify = "6.1"
glob = "0.3"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.100"
regex = "1.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
